CREATE DATABASE QUAN_HUONG_TRAM
GO

USE QUAN_HUONG_TRAM
GO

---TABLE KHACHHANG---
--MAKH: Mã khách hàng
--HOTEN: Họ tên
--DCHI: Địa chỉ
--SODT: Số điện thoại
--NGSINH: Ngày sinh
--NGDK: Ngày đăng ký thành viên
--DOANHSO: Tổng trị giá các hóa đơn khách hàng đã mua
CREATE TABLE KHACHHANG (
	MAKH CHAR(4),
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY
)
GO

CREATE TABLE NHANVIEN (
	MANV CHAR(4),
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
)
GO

CREATE TABLE SANPHAM (
	MASP CHAR(4),
	TENSP CHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
)
GO

CREATE TABLE HOADON (
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY
)
GO

CREATE TABLE CTHD (
	SOHD INT,
	MASP CHAR(4),
	SL INT
)
GO

--CAU 1:
--Tạo các quan hệ và khai báo các khóa chính, 
--khóa ngoại của quan hệ.

--Them khóa chính cho bảng KHACHHANG
ALTER TABLE KHACHHANG
ALTER COLUMN MAKH CHAR(4) NOT NULL
GO

ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
GO

--Them khóa chính cho bảng NHANVIEN
ALTER TABLE NHANVIEN
ALTER COLUMN MANV CHAR(4) NOT NULL
GO

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
GO

--Them khóa chính cho bảng SANPHAM
ALTER TABLE SANPHAM
ALTER COLUMN MASP CHAR(4) NOT NULL
GO

ALTER TABLE SANPHAM
ADD CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
GO

--Them khóa chính cho bảng HOADON
ALTER TABLE HOADON
ALTER COLUMN SOHD INT NOT NULL
GO

ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY (SOHD)
GO

--Thêm khóa ngoại cho bảng HOADON
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO

--Thêm khóa ngoại cho bảng CTHD
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)
GO

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
GO

--Câu 2:
--SOHD là số tự tăng. Bắt đầu là 1001
ALTER TABLE HOADON
ALTER COLUMN SOHD INT IDENTITY(1001,1)
GO



--TEST
SELECT * FROM KHACHHANG
GO
SELECT * FROM NHANVIEN
GO
SELECT * FROM SANPHAM
GO
SELECT * FROM HOADON
GO
SELECT * FROM CTHD

CREATE TABLE PERSON (
	PERSON_ID CHAR(4) PRIMARY KEY,
	LastName varchar(40) 
)

SELECT * FROM PERSON